env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

language: ruby

rvm:
  - 2.4.0

before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.4.0@global bundler
  - gem install bundler -v 1.15.1
  - bundle install --without production

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec bin/rspec spec/controllers
  - bundle exec bin/rspec spec/features
  - bundle exec bin/rspec spec/models
  - bundle exec bin/rspec spec/requests
  - bundle exec bin/rspec spec/routing
  # - bundle exec bin/rspec spec/views
  
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
  