language: ruby

rvm:
  - 2.3.1

before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.3.1@global bundler
  - gem install bundler -v 1.10.6
  - bundle install

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -U postgres -c "CREATE USER ramax WITH CREATEUSER PASSWORD 'ramax';"
  - psql -U postgres -c "ALTER USER ramax CREATEDB;"
  - psql -U postgres -c "CREATE DATABASE db_test_psql OWNER ramax;"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  # TODO: some rspec tests are not passes
  #- bundle exec rspec spec/comtrollers
  #- bundle exec rspec spec/views/posts
  - bundle exec rspec spec/models
  - bundle exec rspec spec/request
  - bundle exec rspec spec/views/dashboard

addons:
  code_climate:
    repo_token: c7fc03050a8073a515773721fbb1de32da8ab236a6fb8cc06aea06cdcabd21e7
  postgresql: "9.3"

services:
  - postgresql
