language: ruby
rvm:
  - 2.2.3
  # - jruby
  # - rbx-2
# cache: bundler
# before_install:
  # - gem install nokogiri -- --with-cflags='--std=gnu99'
  # - gem install bundler -v 1.10.6
  # - bundle update
  # - bundle --version
before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.2.3@global bundler --version 1.12.5
  - gem install bundler -v 1.10.6
  - bundle install
