language: ruby

rvm:
  - 2.4.0

before_install:
  - gem uninstall -i /home/travis/.rvm/gems/ruby-2.4.0@global bundler
  - gem install bundler -v 1.15.1
  - bundle install

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec bin/rspec spec/controllers
  - bundle exec bin/rspec spec/features
  - bundle exec bin/rspec spec/models
  - bundle exec bin/rspec spec/requests
  - bundle exec bin/rspec spec/routing
  # - bundle exec bin/rspec spec/views
  